[Config]
use_emoji = false

[[CommitType]]
name = "Feat"
emoji = "âœ¨"
description = "New feature or functionality added to the code"
release = true

[[CommitType]]
name = "Fix"
emoji = "ğŸ›"
description = "Bug fix"
release = true

[[CommitType]]
name = "Perf"
emoji = "âš¡ï¸"
description = "Code performance improvements"
release = true

[[CommitType]]
name = "Docs"
emoji = "ğŸ“š"
description = "Changes to the documentation"
release = false

[[CommitType]]
name = "Style"
emoji = "ğŸ¨"
description = "Code style changes"
release = false

[[CommitType]]
name = "Refactor"
emoji = "ğŸŒ¿"
description = "Changes without adding features, just quality of the code"
release = false

[[CommitType]]
name = "Remove"
emoji = "ğŸ›‘"
description = "Remove code or files"
release = false

[[CommitType]]
name = "Config"
emoji = "ğŸ”§"
description = "Changes in project configuration"
release = false

[[CommitType]]
name = "Test"
emoji = "ğŸ§ª"
description = "Adding or modifying tests"
release = false

[[CommitType]]
name = "Chore"
emoji = "ğŸŸ¢"
description = "Updating maintenance tasks, dependency updates, etc."
release = false

[[CommitType]]
name = "CI"
emoji = "ğŸ‘·"
description = "Changes to the continuous integration configuration"
release = false

[[CommitType]]
name = "Build"
emoji = "ğŸ“¦"
description = "Changes that affect the build system"
release = false

[[CommitType]]
name = "Initial Commit"
emoji = "ğŸ‰"
description = "First commit"
release = true

[[CommitType]]
name = "Release"
emoji = "ğŸ”–"
description = "Release a new version of the code"
release = true

[[CommitType]]
name = "Merge"
emoji = "ğŸ”€"
description = "Merge branches or pull requests"
release = false

[[CommitType]]
name = "Revert"
emoji = "âª"
description = "Revert to a previous commit"
release = false